import numpy as np
# sys.path.append('..') # Adjust the path to your project structure
from radmc.setup import * # Grid, Model, Setup classes
from radmc.simulate import * # Simulation class

################################################################################
"""
Grid
=================================================
The following code sets up the spherical grid for the simulation.
Other grid types are still under construction.
=================================================
sph_grid():
    The default spherical grid is set to refined at midplane and inner regions.
    ****************************************************************************
    r_bound: 
        Radial bounds of the grid in cm. Default is [1e-2*au, 50*au].
    theta_bound: 
        Polar angle bounds of the grid in radians. Default is [np.pi/8, 7*np.pi/8].
    phi_bound: 
        Azimuthal angle bounds of the grid in radians. Default is [0, 2*np.pi].
    nr: 
        Number of radial grid points. Default is 200.
    ntheta: 
        Number of polar angle grid points. Default is 200.
    nphi: 
        Number of azimuthal angle grid points. Default is 20.
    
    *****************************************************
    Note: Grids of r- and theta-direction are log-spaced, 
        and phi-direction is linear (default as azimuthally symmetric).
    *****************************************************
=================================================
"""
SPH = Grid()
SPH.sph_grid(
    r_bound =[1e-2*au, 50*au],
    theta_bound = [np.pi/8, 7*np.pi/8],
    phi_bound = [ 0, 2*np.pi],
    nr=200,
    ntheta=200,
    nphi=20,
)

################################################################################
"""
Model
=================================================
The following code sets up the model for the simulation.
=================================================
generate_opacity_optool():
    Generates the opacity tables using 'optool' software.
    *****************************************************
    a_max: float (mm)
        Maximum grain size in mm. (a_min is initially set to be 0.01 um = 1e-5 mm)

    composition: str
        If composition is set to 'X22', 
            it will generate the originally opacity tables used in Xu+22 (DSHARP with sublimating effect).,
            i.e., it will generate the opacity tables for 4 temperature regimes,
            seperated by T_crit=[150, 425, 680, 1200] K.
            If temperature is higher than 1200 K, dust will be sublimated. So the opacity will be set to 0. 
            The spec of the dust is:
                ['h2o-w 0.2', 'c-org 0.3966', 'fes 0.0743', 'astrosil 0.3291']
                'h2o-w' is water ice, 'c-org' is organic carbon, 'fes' is iron sulfide, and 'astrosil' is silicate.
                The following number is the mass fraction.
                When the temperature is lower than 150 K (T_crit[0]), four species will contribute to the opacity.
                Once the temperature is higher than T_crit[i], only the last 4-i species will contribute to the opacity.
                Then the fraction will automatically be normalized to 1.
            The opacity tables will be saved in the './kappa/' directory. (Can be changed with the 'table_cache' parameter)
        If composition is set to 'dsharp',
            it will generate the opacity tables used in DSHARP survey.
        Utility of customizing dust composition is still under construction.

    inputstyle: int
        1 : dustkappa_*.inp file
        10: dustkapscatmat_*.inp file without grain alignment (read Z matrix)
        20: dustkapscatmat_*.inp file with grain alignment (required dustkapalignfact_*.inp)
---------------------------------------------------------------------------------
combine_opacity_tables():
    Combines the opacity tables generated by generate_opacity_optool() into one table which X22 model adopts.
    *****************************************************************************************************
    opacity_tables: list of optool.particle() objects
        List of opacity tables to be combined. The elements should be the output of optool.particle().

    T_crit: list of float (K)
        List of critical temperatures that separate the temperature regimes.

    fraction: list of float
        List of mass fractions of the dust species in each temperature regime.

    *****************************************************
    Note: The length of T_crit and fraction should be the same, 
        and the length should be equal to the length of opacity_tables.
    *****************************************************
---------------------------------------------------------------------------------
read_opacity_table():
    Reads the opacity table and transform to the format required by the X22 model.
    ******************************************************************************************
    p: optool.particle() object
        The output of optool.particle()
---------------------------------------------------------------------------------
X22():
    Generates the X22 model (data maps) with the given parameters.
    ***After this function, interp_model_to_grid() should be called to interpolate the model to the grid.
    *****************************************************************************************************
    opacity_table: opacity table
        The output of combine_opacity_tables() or read_opacity_table().

    Mass_of_star: float (solar mass; Default is 0.5)
        Mass of the central star in solar masses.

    Accretion_rate: float (solar mass per year; Default is 5e-4)
        Accretion rate in solar mass per year.

    Radius_of_disk: float (au; Default is 35)
        Radius of the disk in au.

    Q: float (Default is 1.5)
        Toomre Q parameter.
---------------------------------------------------------------------------------
uniform_sphere():
    Generates a uniform sphere with the given parameters and Grid class (in spherical coords).
    No need to call interp_model_to_grid() after this function.
    ******************************************************************************************
    dust_to_gas_ratio: float (Default is 0.01.)
        Dust to gas mass ratio. 

    rho: float (g/cm^3; Default is 1e-12)
        Total (dust+gas) density of the sphere. 
        Dust density will be set to the same value simply multiplied by the dust_to_gas_ratio.

    temperature: float (K; Default is 10)
        Temperature of the sphere.

    sph_grid: Grid class
        The spherical grid to be used. Default is the SPH grid defined above.
---------------------------------------------------------------------------------
interp_model_to_grid():
    Interpolates the model to the given grid.
    *****************************************
    grid: Grid class
        The grid to be used. 
=================================================
"""
#### Parameters for the inner layer of the disk model ##########################
amax_inner          = 1.0
inputstyle_index    = 20
mdot                = 5e-4
rd                  = 35
Toomre_Q            = 0.7
################################################################################
model = Model()
model.generate_opacity_optool(a_max=amax_inner, composition='X22', inputstyle=inputstyle_index) # a_max in mm
opacity_tables = []
opacity_dir = ['temp_regime_1', 'temp_regime_2', 'temp_regime_3', 'temp_regime_4']
for dir in opacity_dir:
    p = optool.particle('',
                        cache=f'./kappa/{dir}/',
                        silent=True)
    opacity_tables.append(p)

inner_opacity = model.combine_opacity_tables(opacity_tables = opacity_tables,
                            T_crit=[150, 425, 680, 1200],
                            fraction=[0.2, 0.3966, 0.0743, 0.3291],)
x22model = model.X22(
    opacity_table=inner_opacity,
    Mass_of_star=0.5,
    Accretion_rate=mdot,
    Radius_of_disk=rd,
    Q=Toomre_Q,
)
################################################################################
###### Multi-layered disk model ################################################
"""
If you want to set up a multi-layered disk model, here is an example.
In this example, the outer layer is set to another X22 model but with smaller dust grains.
The seperation now is set to be 150 K (water snowline), substituting the first temperature regime of the inner layer.

"""
amax_outer         = 0.01
outer_model = Model()
outer_model.generate_opacity_optool(a_max=amax_outer, composition='dsharp', inputstyle=inputstyle_index)
p = optool.particle('',
                    cache='./kappa/dsharp/',
                    silent=True)
outer_opacity = outer_model.read_opacity_table(p,)
outer_layer = outer_model.X22(
    opacity_table=outer_opacity,
    Mass_of_star=0.5,
    Accretion_rate=mdot,
    Radius_of_disk=rd,
    Q=Toomre_Q,
)

rho = model.rho_dust
rho[:, :, :, 0] = outer_model.rho_dust[:, :, :, 0]
model.rho_dust = rho
################################################################################
model.interp_model_to_grid(grid=SPH)
################################################################################
"""
Setup
=================================================
The following code sets up the simulation parameters and writes the necessary files for the simulation.
---------------------------------------------------------------------------------
Setup():
    *****************************************
    model_class: Model class
        The model class to be used.

    grid_class: Grid class
        The grid class to be used. (Grid class)

    silent: bool
        If True, the setup will not print any messages. Default is True.
=================================================
get_mastercontrol():
    Preparing the master control file for radmc3d.
    *****************************************************
    filename : str (default: radmc3d.inp)
        output filename. 
        It will still creat a file with default name, but will duplicate an output file with the specified name.

    comment : str (default: None)
        comment to add to the file header 

    incl_dust : 0/1/None  
        0: force not include dust/ 1: force include / None: let radmc3d determine

    incl_lines : 0/1/None 
        0: force not include line/ 1: force include / None: let radmc3d determine

    nphot : int (default: 1000000)
        The number of photon packages used for the thermal Monte Carlo simulation 

    nphot_scat : int (default: 1000000)
        The number of photon packages for the scattering Monte Carlo simulations, done before image-rendering

    scattering_mode_max : 0/1/2/None (default: None)
        0: no scattering / 1: isotropic scattering / 2: full scattering / None: let radmc decide 

    istar_sphere : 0/1 (default: 1)
        If 0/1, treat stars as point-source/sphere 

    num_cpu : int (default: available threads-2)
        number of cpu core to use

    *****************************************************
    Note: Other possible options (including using **kwargs) see
        https://www.ita.uni-heidelberg.de/~dullemond/software/radmc-3d/manual_radmc3d/inputoutputfiles.html
    *****************************************************
---------------------------------------------------------------------------------
get_continuumlambda():
    Preparing the wavelength file (wavelengths are in units of micron).
    This is the file that sets the discrete wavelength points for the continuum radiative transfer calculations.
    If this method is called for multiple times, by default it concatenate the wavelengths in each input,
    unless the input wavelengths do not increase or decrease monotonically. 
    In that case, it gives a warning without editing the files.
    If no lambda_micron is given, it recreates the 'wavelength_micron.inp' file using the default wavelengths.

    Format:
    nlam
    lambda[1]
    ...
    ...
    lambda[nlam]

    https://www.ita.uni-heidelberg.de/~dullemond/software/radmc-3d/manual_radmc3d/inputoutputfiles.html#sec-wavelengths
    *****************************************************
    filename : str (default: wavelength_micron.inp).
        output filename. 
        It will still creat a file with default name,
        but will duplicate an output file with the specified name.

    comment  : str (default: None)
        comment to add to the file header.

    lambda_micron : numpy array (um)
        wavelength to calculate continuum.

    append : bool (default: False)
        if False, remove the existing wavelength_micron.inp and ignore any information in it.

    *****************************************************
    Note: Wavelengths must be monotonically increasing/decreasing.
    *****************************************************

    *****************************************************
    Note: Wavelength coverage must include the wavelengths at which the stellar spectra have most of their energy, 
        and at which the dust cools predominantly. This in practice means that this should go all the way from 
        0.1 micron to 1000 micron
    *****************************************************
---------------------------------------------------------------------------------
write_amr_grid():
    Writes the AMR grid file for the simulation.
    This file contains the grid information for the simulation.
----------------------------------------------------------------------------------
write_dust_opac():
    Writes the dust opacity file for the simulation.
    This file contains the dust opacity information for the simulation.
    *****************************************************
    dust_type: list of str
        This will copy the dust opacity files from the ./kappa/<dust_type> directory, 
        and rename them to dustkappa_<dust_type>.inp or dustkapscatmat_<dust_type>.inp.
    
    inputstyle: int (default: 20)
        1 : dustkappa_*.inp file
        10: dustkapscatmat_*.inp file without grain alignment (read Z matrix)
        20: dustkapscatmat_*.inp file with grain alignment (required dustkapalignfact_*.inp)
    *****************************************************

    *****************************************************
    Note: grain_align will be set to True if inputstyle is 20.
    *****************************************************
----------------------------------------------------------------------------------
write_density_file():
    Writes the density file for the simulation.
    This file contains the density information for the simulation.
----------------------------------------------------------------------------------
write_temperature_file():
    Writes the temperature file for the simulation.
    This file contains the temperature information for the simulation.
----------------------------------------------------------------------------------
get_dustalignmentcontrol():
    Writes the dust alignment control file for the simulation.
    This file contains the dust alignment control information for the simulation.
    *****************************************************
    uniform_*: bool (default: True/False)
        If True, the dust alignment will include uniform field the specified direction.
    
    hourglass: bool (default: False)
        If True, there is additional hourglass field x and y directions with strength of 
        alpha * x * z * np.exp(-alpha * z**2) and
        alpha * y * z * np.exp(-alpha * z**2) respectively.

    alpha: float (default: 1/(10*au*au))
        The strength of the hourglass field.
    
    toroidal: bool (default: False)
        If True, there is additional toroidal field in the x and y direction with strength of
        y and -x respectively.
=================================================
"""
################################################################################
setup = Setup(model_class=model, grid_class=SPH, silent=True)
setup.get_mastercontrol(filename=None,
                        comment=None,
                        incl_dust=1,
                        incl_lines=0,
                        nphot=500000,
                        nphot_scat=5000000,
                        nphot_spec=500000,
                        scattering_mode_max=5,
                        istar_sphere=1,
                        num_cpu=None,
                        modified_random_walk = 1,
                        alignment_mode=-1, # -1 for grain alignment
                        )
setup.get_continuumlambda(filename=None,
                        comment=None,
                        lambda_micron=None,
                        append=False,
                        silent=True)
setup.write_amr_grid()
setup.write_dust_opac(dust_type=['dsharp']+opacity_dir[1:], inputstyle=inputstyle_index, grain_align=True)
setup.write_density_file()
setup.write_temperature_file()
setup.get_dustalignmentcontrol( uniform_z=True, 
                                uniform_x=False, 
                                uniform_y=False,
                                hourglass=False,
                                alpha=1/(10*au*au),  
                                toroidal=False)
################################################################################
"""
Simulation
"""
crop_sizeau = 200  # Size of the cropped image in au
obs_wav = np.array([
    1300, 
    3000, 
    7000, 
    18000
])
save_dir = 'assigned_directory'  # Directory to save the simulation results


simulation = Simulation(save_out=True, save_npz=False)
simulate_mutual_parms = {
    "incl"      : 50,
    "npix"      : 500,
    "sizeau"    : crop_sizeau,
    "posang"    : 0,
    "phi"       : 0,
    "dir"       : f'{save_dir}/',
}
simulation.generate_continuum(
    scat=True,
    stokes=True,
    read_lambda=obs_wav*1e-3,
    load_simulation=False,
    fname=f'conti',
    **simulate_mutual_parms
) 
# simulation.conti is the output of readImage()
simulation.generate_sed(
    scat=True,
    read_lambda=obs_wav*1e-3,
    load_simulation=False,
    fname='sed',
    **simulate_mutual_parms
) 
# simulation.spectrum is the output of readSpectrum()
